#ID15 - EKS EFS Validation

diff --git a/ci-mvp-downstream-builds/downstream-build-2/Jenkinsfile b/ci-mvp-downstream-builds/downstream-build-2/Jenkinsfile
--- a/ci-mvp-downstream-builds/downstream-build-2/Jenkinsfile
+++ b/ci-mvp-downstream-builds/downstream-build-2/Jenkinsfile
@@ -160,9 +160,9 @@ spec:
       steps {
         container('runner') {
           sh """
-            echo "📤 Uploading to S3..."
-            aws s3 cp /home/jenkins/agent/${BUILD_BUNDLE_DUMMY_NAME} \
-                  ${env.AWS_S3_URL_TESTS}/${BUILD_BUNDLE_DUMMY_NAME} || echo "❌ Upload failed"
+            echo "📤 Uploading tests to S3..."
+            aws s3 cp /home/jenkins/agent/${TEST_DUMMY_NAME} \
+                  ${env.AWS_S3_URL_TESTS}/${TEST_DUMMY_NAME} || echo "❌ Upload failed"
           """
         }
       }
