#ID15 - EKS EFS Validation

diff --git a/ci-mvp-downstream-builds/Jenkinsfile b/ci-mvp-downstream-builds/Jenkinsfile
--- a/ci-mvp-downstream-builds/Jenkinsfile
+++ b/ci-mvp-downstream-builds/Jenkinsfile
@@ -48,8 +48,17 @@ spec:
     AWS_S3_URL_ARTIFACTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.BUILD_NUMBER}/artifacts"
     AWS_S3_URL_TESTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.BUILD_NUMBER}/tests"
 
+    BUILD_BUNDLE_NAME='liferay-portal-bundle-tomcat.tar.gz'
+    BUILD_SOURCE_NAME='liferay-portal-source.tar.gz'
+
+    BUILD_BUNDLE_DUMMY_NAME='dummy-${BUILD_BUNDLE_NAME}'
+    BUILD_SOURCE_DUMMY_NAME='dummy-${BUILD_SOURCE_NAME}'
+
     // s3://liferayci-file-propagator-mvp/build/35/artifacts
     // s3://liferayci-file-propagator-mvp/build/35/tests
+
+    // liferay-portal-bundle-tomcat.tar.gz  (~1.7gb)
+    // liferay-portal-source.tar.gz         (~1.2gb)
 
   }
 
@@ -119,16 +128,16 @@ spec:
         //   ])
         // }
 
-          sh '''
+          sh """
 
             echo "🔍 Checking EFS mount at /home/jenkins/agent"
             mount | grep /home/jenkins/agent || echo "❌ EFS NOT mounted"
 
-            date > /home/jenkins/agent/git-repo-emulation-gz.txt
-            echo "📄 GitRepo emulation ." >> /home/jenkins/agent/git-repo-emulation-gz.txt
+            date > /home/jenkins/agent/${BUILD_SOURCE_DUMMY_NAME}
+            echo "📄 GitRepo emulation ." >> /home/jenkins/agent/${BUILD_SOURCE_DUMMY_NAME}
 
             ls -al /home/jenkins/agent
-          '''
+          """
         
       }
     }
@@ -187,8 +196,8 @@ spec:
         container('runner') {
           sh """
             echo "📤 Uploading to S3..."
-            aws s3 cp /home/jenkins/agent/git-repo-emulation-gz.txt \
-              ${env.AWS_S3_URL_ARTIFACTS}/git-repo-emulation-gz.txt || echo "❌ Upload failed"
+            aws s3 cp /home/jenkins/agent/${BUILD_BUNDLE_DUMMY_NAME} \
+              ${env.AWS_S3_URL_ARTIFACTS}/${BUILD_BUNDLE_DUMMY_NAME} || echo "❌ Upload failed"
           """
         }
       }
