#ID15 - EKS EFS Validation

diff --git a/ci-mvp-downstream-builds/Jenkinsfile b/ci-mvp-downstream-builds/Jenkinsfile
--- a/ci-mvp-downstream-builds/Jenkinsfile
+++ b/ci-mvp-downstream-builds/Jenkinsfile
@@ -133,9 +133,12 @@ spec:
             echo "🔍 Checking EFS mount at /home/jenkins/agent"
             mount | grep /home/jenkins/agent || echo "❌ EFS NOT mounted"
 
+            date > /home/jenkins/agent/${BUILD_BUNDLE_DUMMY_NAME}
+            echo "📄 GitRepo emulation ." >> /home/jenkins/agent/${BUILD_BUNDLE_DUMMY_NAME}
+
             date > /home/jenkins/agent/${BUILD_SOURCE_DUMMY_NAME}
             echo "📄 GitRepo emulation ." >> /home/jenkins/agent/${BUILD_SOURCE_DUMMY_NAME}
-
+            
             ls -al /home/jenkins/agent
           """
         
@@ -197,8 +200,12 @@ spec:
         container('runner') {
           sh """
             echo "📤 Uploading to S3..."
+
             aws s3 cp /home/jenkins/agent/${BUILD_BUNDLE_DUMMY_NAME} \
               ${env.AWS_S3_URL_ARTIFACTS}/${BUILD_BUNDLE_DUMMY_NAME} || echo "❌ Upload failed"
+
+            aws s3 cp /home/jenkins/agent/${BUILD_SOURCE_DUMMY_NAME} \
+              ${env.AWS_S3_URL_ARTIFACTS}/${BUILD_SOURCE_DUMMY_NAME} || echo "❌ Upload failed"
           """
         }
       }
