#ID15 - EKS EFS Validation

diff --git a/ci-mvp-downstream-builds/Jenkinsfile b/ci-mvp-downstream-builds/Jenkinsfile
--- a/ci-mvp-downstream-builds/Jenkinsfile
+++ b/ci-mvp-downstream-builds/Jenkinsfile
@@ -134,6 +134,20 @@ spec:
     }
 
 
+  
+    stage('Upload to S3') {
+      steps {
+        container('runner') {
+          sh """
+            echo "📤 Uploading to S3..."
+            aws s3 cp /home/jenkins/agent/git-repo-emulation-gz.txt \
+              ${env.AWS_S3_URL_ARTIFACTS}/git-repo-emulation-gz.txt || echo "❌ Upload failed"
+          """
+        }
+      }
+    }
+
+
     stage('Decide What to Run') {
       steps {
         script {
@@ -173,18 +187,6 @@ spec:
       }
     }
 
-  
-    stage('Upload to S3') {
-      steps {
-        container('runner') {
-          sh """
-            echo "📤 Uploading to S3..."
-            aws s3 cp /home/jenkins/agent/git-repo-emulation-gz.txt \
-              ${env.AWS_S3_URL_ARTIFACTS}/git-repo-emulation-gz.txt || echo "❌ Upload failed"
-          """
-        }
-      }
-    }
 
 
 
